config/routes.rb
VoyageX::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'auth/omniauth_callbacks',
                            registrations: "auth/registrations",
                            sessions: "auth/sessions" }
  devise_scope :user do
    match '/auth/:provider', to: 'sessions#create', via: [:get, :post], as: :authentication
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :authentication_callback
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/auth/facebook/disconnect', to: 'users#disconnect_from_facebook', via: [:get, :post]
    match '/auth/twitter/disconnect', to: 'users#disconnect_from_twitter', via: [:get, :post]
  end

  mount Resque::Server, at: '/4hfg398dmmnrf/resque', as: :resque_admin
  
  mount Comm::Engine => "/comm" unless Rails.env == 'test'

  resources :users, only: [:update] do
  end
  get '/users', to: 'users#users', as: :users
  get '/unread_chat_messages', to: 'users#unread_chat_messages', as: :unread_chat_messages
  put '/chat_message_received/:id', to: 'users#chat_message_received', as: :chat_message_received

  get '/location_bookmarks', to: 'main#index'
  get '/location_data/:location_id', to: 'main#location_data', as: :location_data
  get '/pois/:lat/:lng', to: 'pois#pois', as: :pois, constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                    lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  post '/sync_pois', to: 'pois#sync_pois', as: :sync_pois
  match '/pull_pois/:lat/:lng/:radius', to: 'pois#pull_pois', as: :pull_pois,
                                                              via: [:get, :post],
                                                              constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                             lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  
  get '/manifest', to: 'main#manifest', as: :manifest
  match '/set_user_detail/:detail', to: 'users#change_details', as: :set_user_detail, via: [:get, :post]
  delete '/set_user_detail/:detail', to: 'users#delete_details'
  get '/csrf', to: 'pois#csrf', as: :csrf
  get '/poi_comments/:poi_id/:poi_note_id', to: 'pois#comments', as: :poi_comments
  get '/ping/:key', to: 'comm/comm#ping', as: :comm_ping
  put '/register', to: 'comm/comm#register', as: :comm_register

  get '/test/javascript', to: 'test#javascript', as: :test_javascript

  get '/thesis', to: 'thesis#index', as: :thesis
  
  root to: 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include ::AuthUtils
  include ::GeoUtils

  # used from Model.js to act withLocation
  # api-call
  def location_data
    location = Location.find(params[:location_id])
    location_json = {lat: location.latitude, lng: location.longitude, address: shorten_address(location)}
    poi = Poi.where(location_id: location.id).first
    location_json[:poi_id] = poi.id if poi.present?
    render json: location_json.to_json
  end

  def index
    @initial_subscribe = true
    unless tmp_user.foto.exists?
      foto = UserHelper::fetch_random_avatar request
      foto = File.open("#{Rails.root}/spec/support/images/foto.png", 'r') unless foto.present?
      tmp_user.update_attribute(:foto, foto) 
    end
    if signed_in? # registered_user?
      unless tmp_user.snapshot.cur_commit.present?
        vm = VersionManager.new Poi::MASTER, Poi::WORK_DIR_ROOT, tmp_user, false#user.is_admin?
        cur_commit = Commit.where(hash_id: vm.cur_commit).first
        cur_commit = User.admin.commits.create(hash_id: vm.cur_commit, timestamp: DateTime.now) unless cur_commit.present?
        tmp_user.snapshot.update_attribute :cur_commit, cur_commit
      end
    end

    nearby_m = (tmp_user.search_radius_meters||20000)
    location = tmp_user.snapshot.location.present? ? tmp_user.snapshot.location : tmp_user.last_location
    if location.present?
      load_location_data location, nearby_m
    else
      @pois = []
      @uploads = []
    end
  end

  # chrome://appcache-internals/
  def manifest
    render 'voyagex.mf', layout: false, content_type: 'text/cache-manifest'
  end

  private

  def load_location_data location, nearby_m
    limits = lat_lng_limits location.latitude, location.longitude, nearby_m
    limits_lat = limits[:lat_south] > limits[:lat_north] ? limits[:lat_north]..limits[:lat_south] : limits[:lat_south]..limits[:lat_north]
    limits_lng = limits[:lng_east] > limits[:lng_west] ? limits[:lng_west]..limits[:lng_east] : limits[:lng_east]..limits[:lng_west]
    @pois = Poi.joins(:location).where(locations: {latitude: limits_lat, longitude: limits_lng})
    @uploads = Upload.joins(attached_to: { poi: :location }).where(locations: {latitude: limits_lat, longitude: limits_lng})
  end
end

app/helpers/main_helper.rb
module MainHelper
  include ::ApplicationHelper
  include ::GeoUtils
  
  def comment_attachment_to_view poi_note
    upload_entity_to_view poi_note.attachment
  end

  def upload_entity_to_view upload
    if upload.entity.is_a? UploadEntity::Mediafile
      case upload.entity.content_type.match(/^[^\/]+/)[0]
      when 'image' 
        max_width = 100
        image_tag upload.entity.file.url, style: "width:#{max_width.to_i}px;" 
      when 'audio'
        content_tag(:audio, upload.entity.id.to_s, controls: 'controls') do
          inner_html = content_tag :source, nil, src: upload.entity.file.url, type: upload.entity.file.content_type
          inner_html += 'Your browser does not support the audio element.'
          inner_html
        end
      when 'video'
        content_tag(:video, upload.entity.id.to_s, controls: 'controls') do
          inner_html = content_tag :source, nil, src: upload.entity.file.url, type: upload.entity.file.content_type
          inner_html += 'Your browser does not support the video element.'
          inner_html
        end
      else
        "unable to display entity with content_type: #{upload.entity.content_type}"
      end
    elsif upload.entity.is_a? UploadEntity::Embed
      case upload.entity.embed_type.match(/^[^\/]+/)[0]
      when 'image' 
        max_width = 100
        image_tag upload.entity.text, style: "width:#{max_width.to_i}px;" 
      else
        "unable to display entity with content_type: #{upload.entity.content_type}"
      end
    else
      'unable to display entity'
    end
  end

  def upload_entity_preview_url upload
    if upload.entity.is_a? UploadEntity::Mediafile
      case upload.entity.content_type.match(/^[^\/]+/)[0]
      when 'image' 
        upload.file.url
      when 'audio'
        VoyageX.IMAGES_PREVIEW_AUDIO_PATH
      when 'video'
        VoyageX.IMAGES_PREVIEW_VIDEO_PATH
      else
        VoyageX.IMAGES_PREVIEW_NA_PATH
      end
    elsif upload.entity.is_a? UploadEntity::Embed
      case upload.entity.embed_type.match(/^[^\/]+/)[0]
      when 'image' 
        upload.entity.text
      else
        VoyageX.IMAGES_PREVIEW_NA_PATH
      end
    else
      VoyageX.IMAGES_PREVIEW_NA_PATH
    end
  end

end

app/views/main/_context_nav_panel.html.haml
.modal
  .modal-dialog#context_nav_panel
    .modal-body
      %ul
        %li
          = link_to 'Points of Interest', '#pois_preview', id: 'pois_preview_btn'
        %li
          = link_to 'Bookmarked Locations', '#location_bookmarks', id: 'location_bookmarks_btn'
        %li
          = link_to 'People of Interest', '#people_of_interest', id: 'people_of_interest_btn'
      #pois_preview
        -#= render partial: 'pois_preview'
      #location_bookmarks
        = render partial: 'location_bookmarks', locals: {user: tmp_user}
      #people_of_interest
        = render partial: 'people_of_interest', locals: {user: tmp_user}

= render partial: 'tmpl_pois_preview'
= render partial: 'tmpl_location_bookmarks'
= render partial: 'tmpl_people_of_interest'

app/views/main/_context_nav_panel.mobile.html.haml
#context_nav_panel{data: {role: 'panel', dismissible: 'false', animate: 'true', display: 'overlay'}}
  %div{style: 'float: right; z-index: 9999; position: absolute; top: 5px; right: 5px; padding: 0px 0px 0px 10px;'}
    %span.ui-icon.ui-icon-circle-close{onclick: '$("#context_nav_panel").panel("close");'}
  #context_nav_tabs
    -#{data: {role: 'tabs'}, style: 'margin-top: 20px;'}
    -#%div
      -#{data: {role: 'navbar'}}
    %ul
      %li{style: 'width: 45px; height: 37px;'}
        = link_to '', '#pois_preview', style: 'width: 35px; height: 35px; margin: 0px; padding: 0px 5px 0px 5px;', data: {role: 'button', icon: 'location'}, id: 'pois_preview_btn'
      %li{style: 'width: 45px; height: 37px;'}
        = link_to '', '#location_bookmarks', style: 'width: 35px; height: 35px; margin: 0px; padding: 0px 5px 0px 5px;', data: {role: 'button', icon: 'eye'}, id: 'location_bookmarks_btn'
      %li{style: 'width: 45px; height: 37px;'}
        = link_to '', '#people_of_interest', style: 'width: 35px; height: 35px; margin: 0px; padding: 0px 5px 0px 5px;', data: {role: 'button', icon: 'user'}, id: 'people_of_interest_btn'
      %li{style: 'height: 37px; padding: 0px 0px 0px 50px;'}
        %span{style: 'float: right;'}
          = image_tag 'fullscreen_on.png', id: 'fullscreen_mode_icon_on', onclick: 'GUI.toggleFullScreen(true)', style: 'display: none; max-height: 35px;'
          = image_tag 'fullscreen_off.png', id: 'fullscreen_mode_icon_off', onclick: 'GUI.toggleFullScreen(false)', style: 'max-height: 35px;'
    #pois_preview
      -#= render partial: 'pois_preview'
    #location_bookmarks
      = render partial: 'location_bookmarks', locals: {user: tmp_user}
    #people_of_interest
      = render partial: 'people_of_interest', locals: {user: tmp_user}

= render partial: 'tmpl_pois_preview'
= render partial: 'tmpl_location_bookmarks'
= render partial: 'tmpl_people_of_interest'

app/views/main/_home.mobile.html.haml
%fieldset.upload_source_select{data: {role: 'controlgroup', type: 'horizontal'}}
  %input{type: 'radio', id: 'home_administration', name: 'home', value: 'administration', checked: true, onclick: 'GUI.toggleHomeTab(this)'}
  = label_tag 'home_administration', 'Administration'
  %input{type: 'radio', id: 'home_stats', name: 'home', value: 'stats', onclick: 'GUI.toggleHomeTab(this)'}
  = label_tag 'home_stats', 'Stats'
  %input{type: 'radio', id: 'home_help', name: 'home', value: 'help', onclick: 'GUI.toggleHomeTab(this)'}
  = label_tag 'home_help', 'Help'
.messages
  #upload_error
  #upload_message
  #upload_progress
#administration
  %div{style: 'float :left; padding: 13px 0px 13px 0px;'}
    %span#whoami_img_container
      %span#whoami_img_edit{style: 'display: none'}
      %span#whoami_img_nedit
    #user_foto_input_container{style: 'display:none;'}
      = render partial: '/users/foto.mobile', locals: {user: tmp_user()}
    %br
    %span#whoami_form{style: 'display: none'}
      - @_details = [:username]
      = render('/users/edit_details')
    %span#whoami_edit
    %span#whoami_nedit{style: 'display: none'}
  .auth_ctrl{style: 'float: left; padding: 10px 0px 0px 5px;'}
    .logout-link{style: "display: #{user_signed_in? ? 'block' : 'none'}; padding: 13px 0px 0px 0px;"}
      = link_to t('auth.sign_out'), destroy_user_session_path, style: 'margin-left: 20px;', data: { remote: "true", format: :js, method: :delete }
    #sign_up_or_in{style: "display: #{user_signed_in? ? 'none' : 'inline'};"}
      - popup_params = { data: { rel: 'popup', 'position-to' => 'window', 'data-role' => 'button' } }
      .login-link
        = link_to t('auth.sign_in'), '#sign_in_modal', popup_params
      %br
      .reg-link
        = link_to t('auth.sign_up'), '#sign_up_modal', popup_params
      - if Rails.env.to_sym == :development || true
        %br
        .omniauth-links
          .button.facebook_login
            -# , origin: "#{request.env['rack.url_scheme']}://#{request.env['HTTP_HOST']}#{request.env['REQUEST_URI']}"
            = link_to "#{user_omniauth_authorize_path(:facebook)}#c=" do
              = image_tag 'facebook-icon.png', style: 'width: 25px; height: 25px;'
  #lang_select{style: 'float: right;'}
    - lcls = lang_change_links request, ['c']
    %div{style: 'margin: 10px 10px 0px 0px;'}
      = link_to image_tag("en.png", style: "border-width:0px;width:30px;height:20px;"), '#', onclick: "javascript:document.location.href=VIEW_MODEL.linkForView('#{lcls[0]}', 'en', '#{lcls[1]}');", :style => "color:#00dd;"
    %br
    %div{style: 'margin: 5px 10px 0px 0px;'}
      = link_to image_tag("de.png", style: "border-width:0px;width:30px;height:20px;"), '#', onclick: "javascript:document.location.href=VIEW_MODEL.linkForView('#{lcls[0]}', 'de', '#{lcls[1]}');", :style => "color:#00dd;"
  = render partial: '/users/settings.mobile'
= render partial: '/main/stats.mobile'

app/views/main/_location_bookmarks.html.haml
- if is_mobile
  %h4
    Bookmarked Locations
-#
  TODO: filter: von mir kommentiert. alternativ: eigener tab dafür
  3 Arten:
  %ul
    %li
      mit poi - von mir kommentiert
    %li
      mit poi - ohne kommentar von mir
    %li
      ohne poi
%table{style: 'border-spacing: 5px;'}
  %tr
    %th
      Mediafile
    %th
      Last Bookmark
    %th
      Kommentiert
    -#%th
    -#  Addresse

app/views/main/_media_input_panel.html.haml
#media_input_panel{data: {role: 'panel', dismissible: 'false', animate: 'true', display: 'overlay'}}
  .ctrls_bar
    %span.btn{id: 'switch_camera', style: 'float: left;'}
      = image_tag('switch-camera.png', style: 'margin: 12px 0px 0px 20px;')
    .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{id: 'media_input_stop_btn', style: 'float: right;'}
      .ui-button-text
        Stop

  %video{id: 'media_input_capture', autoplay: true}
  %canvas{id: 'media_input_display', style: 'display: none;'}

  .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{id: 'media_input_capture_btn'}
    .ui-button-text
      #{t('uploads.take_shot').html_safe}

app/views/main/_people_of_interest.html.haml
-#
  if is_mobile
  %h4
    People of Interest
= t('peers.people_of_interest')
%br
%h4{colspan: 4}
  #{t('admin.i_follow')}
%table

app/views/main/_system_message_panel.html.haml
.modal
  .modal-dialog#system_message_panel
    .modal-body
      #system_message

.modal
  .modal-dialog#system_message_popup
    .modal-body
      #system_message_as_popup

= render partial: '/shared/system_dialog'

app/views/main/_tmpl_people_of_interest.html.haml
%table#tmpl_people_i_follow{style: 'display: none;'}
  -#%tbody#i_follow
  %tr.user-container{data: {userId: '{user_id}'}}
    %td
      %img{tmpl: {src: '{peer_foto_url}'}, style: 'max-width: 35px !important;'}
    %td
      {username}
    %td{width: 15}
      &nbsp;
    %td
      = link_to '{last_location}', '#', onclick: "javascript:APP.showPeer(APP.storage().getUser({user_id}), {id: {lastLocationId}, lat: {lastLat}, lng: {lastLng}, address: '{lastAddress}'.trim()!='' ? '{lastAddress}' : null});"

app/views/main/_tmpl_pois_preview.html.haml
#tmpl_poi_preview{style: 'display: none;'}
  .poi-preview-container{data: {id: '{poiId}'}}
    .poi-info
      -#= link_to '{address}', location_path(location_id: '{locationId}'), data: { remote: 'true', format: :js }
      = link_to '{address}', '#', onclick: 'javascript:APP.loadLocation({id: {locationId}});'
    .poi-preview{style: "width: {maxWidth}px; text-align: center;"}
      .swiper-container{id: "poi_swiper_{poiId}"}
        .swiper-wrapper
          {swipePanel}
      {swipeIcon}
    %hr{style: 'margin: 2px 0px 2px 0px;'}

#tmpl_swipe_icon{style: 'display: none;'}
  = image_tag('swipe.jpg', style: 'width: 35px; height: 35px;')

#tmpl_swiper_slide{style: 'display: none;'}
  -#, address: '{address}'
  %span.swiper-slide{data: {poiId: '{poiId}', poiNoteId: '{poiNoteId}'}, style: 'width: {width}px; height: {height}px;'}
    %img{tmpl: {src: '{attachment_url}'}, style: "width: {width}px; height: {height}px;"}

- max_height = 100.0
- max_width = 300
- swiper_style = "width: #{max_width}px; height: #{max_height.to_i}px;"
= javascript_tag do
  $("head").append("<style type='text/css'>.swiper-container { #{swiper_style} }</style>");

app/views/main/index.html.haml
- if is_mobile
  #content_home{role: 'main', style: 'display: none;'}
    = render partial: '/main/home.mobile'
- else
  #content_home{style: 'display: none;'}
    = render partial: '/users/settings'
    = render partial: '/shared/uploads', locals: {resource: Upload.new, resource_name: :upload}
  
= render partial: '/shared/help'

= render partial: '/users/follow_templates'

= javascript_tag do
  var chatViewHeight = Math.round(($(window).height() - $(".navbar-header").height()) * 0.#{is_mobile ? 7 : 8}) - 10;
  var chatInputHeight = $(window).height() - $(".navbar-header").height() - chatViewHeight;
  $("head").append("<style type='text/css'>.chat_view {width:100%;height:"+chatViewHeight+"px !important;}</style>");
  $("head").append("<style type='text/css'>.chat_input_container {width:"+($(window).width()-35)+"px !important;float: right;}</style>");
  $("head").append("<style type='text/css'>.chat_input, .chat_input_text {width:100%;height:"+chatInputHeight+"px !important;}</style>");

#content_chat{style: 'display: none;'}
  .chat_view
  .bc_controls
    = link_to image_tag('link-poi.png', style: 'height: 32px;', title: t('chat.prompt_poi_id'), alt: t('chat.prompt_poi_id')), '#', onclick: "javascript:APP.view().promptPoiLinkInput('bc');"
  .chat_input_container
    = form_tag '#', method: :post, remote: true
    = text_area_tag :message, '', class: :chat_input

#content_map
  %canvas{id: 'tile_canvas', style: 'display: none; width: 256px; height: 256px;'}
  %canvas{id: 'attachment_canvas', style: 'display: none;'}
  %canvas{id: 'user_foto_canvas', style: 'display: none;'}
  #map

#tmpl_auth_whoami{style: 'display: none;'}
  = t('auth.whoami', username: ':username').html_safe
#tmpl_whoami_edit{style: 'display: none;'}
  = link_to set_user_detail_path(detail: :edit_username), data: { remote: "true", format: :js }, class: 'menu_link' do
    %span.whoami>
      {auth_whoami}
#tmpl_auth_whoami_img{style: 'display: none;'}
  %img{tmpl: {src: '{foto_url}'}, class: 'whoami-img', style: 'max-width: 100px !important; max-height: 100px !important;'}
#tmpl_whoami_img_edit{style: 'display: none;'}
  %a{href: '#edit_whoami_img', onclick: 'javascript:APP.view().toogleUserFotoUpload()'}
    {auth_whoami_img}
#tmpl_myfoto{style: 'display: none;'}
  %img{tmpl: {src: '{foto_url}'}, class: 'whoami-img', style: 'margin: 3px 0px -10px 0px; max-height: 45px;'}

#tmpl_bc_chat_msg{style: 'display: none;'}
  %div{class: 'chat_message chat_message_{meOrOther} triangle-border {toggle}'}
    %img{tmpl: {src: '{foto_url}'}, style: 'float: left; max-width: 35px !important;'}
    {message}

= render partial: 'tmpl_peer_popup'

#tmpl_marker_controls{style: 'display: none;'}
  %div{tmpl: {id: 'marker_controls'}}
    %div{style: 'float: left; margin: 0px 0px 0px 5px;'}
      = link_to image_tag('add-marker.png', style: 'height: 25px;', title: t('pois.add'), alt: t('pois.add')), '#edit_poi', onclick: "javascript:APP.poiNoteInput()"
    -# toggle bookmark
    %div{tmpl: {id: 'save-note'}, style: 'float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
      = link_to image_tag('add-bookmark.png', style: 'height: 25px;', title: t('pois.bookmark'), alt: t('pois.bookmark')), '#', onclick: "javascript:APP.bookmarkLocation()"
    %div{tmpl: {id: 'edit-note'}, style: 'display: none; float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
      = link_to image_tag('edit-note.png', style: 'height: 25px;', title: t('locations.view_note'), alt: t('locations.view_note')), '#', onclick: "javascript:APP.bookmarkLocation()"
    %div{tmpl: {id: 'delete-note'}, style: 'display: none; float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
      = link_to image_tag('delete-bookmark.png', style: 'height: 25px;', title: t('locations.delete_note'), alt: t('locations.delete_note')), '#', onclick: "javascript:APP.deleteBookmark()"
    %div{style: 'float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
      = link_to image_tag('set-home.png', style: 'height: 23px;', title: t('admin.add_homebase'), alt: t('admin.add_homebase')), '#', onclick: "javascript:APP.setHomeBase()"
    %div{style: 'float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
      = link_to image_tag('home.png', style: 'height: 23px;', title: t('admin.show_homebase'), alt: t('admin.show_homebase')), '#', onclick: "javascript:APP.loadLocation({id: APP.user().homebaseLocationId})"
    %div{style: 'float: left; margin: 0px 5px 0px 5px; padding: 0px;'}
      = link_to image_tag('radar.png', style: 'height: 23px;', title: 'radar-settings', alt: 'radar-settings'), '#', onclick: "javascript:APP.radarSettings()"
    -# trace moved to radareditor
      %div{style: 'float: left; margin: 0px 5px 0px 5px; padding: 0px;'}
        %span{id: 'trace-ctrl-start-{user_id}'}
          = link_to image_tag('start_trace.png', style: 'height: 23px;', title: 'start-trace-me', alt: 'start-trace-me'), '#', onclick: "javascript:APP.toggleTrace(APP.user(), {path_key})"
        %span{id: 'trace-ctrl-stop-{user_id}', style: 'display: none;'}
          = link_to image_tag('stop_trace.png', style: 'height: 23px;', title: 'stop-trace-me', alt: 'stop-trace-me'), '#', onclick: "javascript:APP.toggleTrace(APP.user(), {path_key})"
    -#
      %div{style: 'margin: 0px 0px 0px 5px; padding: 0px;'}
        = link_to image_tag('arrow-up-right_off.png', style: 'height: 23px;', title: 'navigator', alt: 'navigator', class: 'context_nav_open_icon'), '#', onclick: "javascript:APP.contextNav()"

#tmpl_note_editor{style: 'display: none;'}
  .note_editor
    %div
      Add Note
    %div{style: 'padding: 0px 0px 5px 0px;'}
      = text_area_tag :note, '{text}', id: 'note_{type}_{id}', class: :note_editor

#tmpl_radar_editor{style: 'display: none;'}
  .radar_editor
    .search_radius{style: 'float: left; padding-left: 5px;'}
      = label_tag 'search_radius_input', t('admin.search_radius')
      -#= form_tag set_user_detail_path(detail: :radar), method: :post, remote: true do
        = text_field_tag :search_radius_meters, '{search_radius_meters}', size: 7, maxlength: 7, data: {role: 'none'}
      %span#search_radius_meters>
        {search_radius_meters} m
      %div{tmpl: {id: 'search_radius_ctrl'}}
    %fieldset{data: {role: 'controlgroup'}, tmpl: {id: 'search_radius_display_fs'}}
      -#
        %div{data: {role: 'fieldcontain'}}
          %select{data: {role: 'flipswitch'}, onchange: 'VIEW_MODEL.toggleSearchRadiusDisplay(this)'}
            %option{value: 'show'} show
            %option{value: 'hide'} hide
      %div
        = radio_button_tag 'search_radius_display', 'show', false, id: ':tmpl', 'tmpl-id' => 'search_radius_display_show', data: {mini: true}, onclick: 'VIEW_MODEL.toggleSearchRadiusDisplay(this)'
        = label_tag 'search_radius_display_show', 'show'
      %div
        = radio_button_tag 'search_radius_display', 'hide', true, id: ':tmpl', 'tmpl-id' => 'search_radius_display_hide', data: {mini: true}, onclick: 'VIEW_MODEL.toggleSearchRadiusDisplay(this)'
        = label_tag 'search_radius_display_hide', 'hide'
    %span{style: 'float: left;'}>
      GPS:&nbsp;
    %span{tmpl: {id: 'toggle_watch_position_off'}}
      = image_tag 'locate_off.png', onclick: "APP.toggleWatchPosition('on')", style: 'max-width: 30px; max-height: 30px;'
    %span{tmpl: {id: 'toggle_watch_position_on', style: 'display: none;'}}
      = image_tag 'locate_on.png', onclick: "APP.toggleWatchPosition('off')", style: 'max-width: 30px; max-height: 30px;'
    %div{style: 'float: right; margin: 0px 25px 0px 5px; padding: 0px;'}
      %span{style: 'float: left;'}>
        #{t('admin.watch_position')}:&nbsp;
      %span{id: 'trace-ctrl-start-{user_id}'}
        = link_to image_tag('start_trace.png', style: 'height: 23px;', title: 'start-trace-me', alt: 'start-trace-me'), '#', onclick: "javascript:APP.toggleTrace(APP.user(), {path_key})"
      %span{id: 'trace-ctrl-stop-{user_id}', style: 'display: none;'}
        = link_to image_tag('stop_trace.png', style: 'height: 23px;', title: 'stop-trace-me', alt: 'stop-trace-me'), '#', onclick: "javascript:APP.toggleTrace(APP.user(), {path_key})"

#tmpl_trace-path_editor{style: 'display: none;'}
  .trace-path_editor
    %div
      {trace-paths}

#tmpl_trace-path_entry{style: 'display: none;'}
  .trace-path_entry{tmpl: {id: 'tp_e_{path_key}'}}
    = link_to '{date}', '#', onclick: "javascript:APP.view().viewTracePath(APP.storage().getUser({user_id}), '{path_key}')"
    &nbsp;
    %div{tmpl: {id: 'hide_trace-path_{path_key}'}, style: 'display: none;'}
      [
      = link_to 'hide', '#', onclick: "javascript:APP.view().hideTracePath('{path_key}')"
      ]
      [
      = link_to image_tag('delete.png', style: 'height: 15px;', title: 'delete', alt: 'delete'), '#', onclick: "javascript:APP.deleteTracePath(APP.storage().getUser({user_id}), '{path_key}')"
      ]