config/routes.rb
VoyageX::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'auth/omniauth_callbacks',
                            registrations: "auth/registrations",
                            sessions: "auth/sessions" }
  devise_scope :user do
    match '/auth/:provider', to: 'sessions#create', via: [:get, :post], as: :authentication
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :authentication_callback
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/auth/facebook/disconnect', to: 'users#disconnect_from_facebook', via: [:get, :post]
    match '/auth/twitter/disconnect', to: 'users#disconnect_from_twitter', via: [:get, :post]
  end

  mount Resque::Server, at: '/4hfg398dmmnrf/resque', as: :resque_admin
  
  mount Comm::Engine => "/comm" unless Rails.env == 'test'

  resources :users, only: [:update] do
  end
  get '/users', to: 'users#users', as: :users
  get '/unread_chat_messages', to: 'users#unread_chat_messages', as: :unread_chat_messages
  put '/chat_message_received/:id', to: 'users#chat_message_received', as: :chat_message_received

  get '/location_bookmarks', to: 'main#index'
  get '/location_data/:location_id', to: 'main#location_data', as: :location_data
  get '/pois/:lat/:lng', to: 'pois#pois', as: :pois, constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                    lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  post '/sync_pois', to: 'pois#sync_pois', as: :sync_pois
  match '/pull_pois/:lat/:lng/:radius', to: 'pois#pull_pois', as: :pull_pois,
                                                              via: [:get, :post],
                                                              constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                             lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  
  get '/manifest', to: 'main#manifest', as: :manifest
  match '/set_user_detail/:detail', to: 'users#change_details', as: :set_user_detail, via: [:get, :post]
  delete '/set_user_detail/:detail', to: 'users#delete_details'
  get '/csrf', to: 'pois#csrf', as: :csrf
  get '/poi_comments/:poi_id/:poi_note_id', to: 'pois#comments', as: :poi_comments
  get '/ping/:key', to: 'comm/comm#ping', as: :comm_ping
  put '/register', to: 'comm/comm#register', as: :comm_register

  get '/test/javascript', to: 'test#javascript', as: :test_javascript

  get '/thesis', to: 'thesis#index', as: :thesis
  
  root to: 'main#index'
end

app/models/user.rb
# show channel_enc_key for users
# User.joins(:comm_port).pluck(:username,:channel_enc_key,:sys_channel_enc_key)
class User < ActiveRecord::Base
  
  LETTERS = ('A'..'Z').to_a.freeze
  NUMBERS = (0..9).to_a.freeze
  MIXED = (LETTERS + NUMBERS).freeze
  ACCEPTED_FOTO_CONTENT_TYPES = ["application/octet-stream",
                                 "image/jpg",
                                 "image/jpeg",
                                 "image/png",
                                 "image/gif",
                                 "image/webp"]
  TEMP_EMAIL_PREFIX = 'verify@voyagex'
  TEMP_EMAIL_REGEX = /\Averify@voyagex/

  has_many :locations_users, dependent: :destroy
  has_many :locations, through: :locations_users
  has_many :uploads
  has_many :commits
  has_many :identities, dependent: :destroy
  has_many :users_groups, inverse_of: :user
  has_many :groups, :through => :users_groups
  has_many :chat_messages
  has_one :comm_port, inverse_of: :user, dependent: :destroy
  has_one :snapshot, class_name: 'UserSnapshot', dependent: :destroy
  belongs_to :home_base, class_name: 'Location', foreign_key: :home_base_id

  has_attached_file :foto,
                    url: '/uploads/:attachment/user_:id/:style/:user_foto_file_id'
  
  validates_attachment :foto, presence: true
  validates_attachment_content_type :foto, content_type: User::ACCEPTED_FOTO_CONTENT_TYPES

  Paperclip.interpolates :user_foto_file_id do |attachment, style|
    "foto_#{attachment.instance.id}.#{attachment.original_filename.match(/[^.]+$/)[0]}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         #:async,
         :confirmable, :omniauthable

  def last_location only_stored = false
   #locations.where(locations: {updated_at: locations.maximum(:updated_at)}).first||home_base||Location.default
    l_l = snapshot.present? ?
            snapshot.location.present? ?
              snapshot.location :
              only_stored ? nil : Location.new(id: -1, latitude: snapshot.lat, longitude: snapshot.lng, address: snapshot.address) :
            nil
    l_l||home_base||Location.default
  end

  def grant_to_follow peer
    comm_peer = comm_port.comm_peers.where(peer: peer).first
    unless comm_peer.present? && comm_peer.granted_by_user
      if comm_peer.present?
        # might already be granted
        comm_peer.update_attribute :granted_by_user, true
      else
        comm_peer = comm_port.comm_peers.create peer: peer, granted_by_user: true
      end
      return true
    end
    false
  end

  def follows? peer
    follows.where(comm_ports: {user_id: peer.id}).present?
  end

  def follows
    #CommPort.joins(:comm_peers).where(comm_peers: { peer_id: id, granted_by_user: true })
    User.joins(comm_port: :comm_peers).where(comm_peers: { peer_id: id, granted_by_user: true })
  end

  def request_grant_to_follow peer
    peer_port = CommPort.where(user: peer).first
    peer_port.comm_peers.create peer: self
  end

  def requested_grant_to_follow
    t = CommPeer.arel_table
    CommPort.joins(:comm_peers, :user).where(t[:peer_id].eq(id).and(t[:granted_by_user].eq(nil).or(t[:granted_by_user].eq(false))))
  end

  # utility method for instant follow
  def follow! user
    comm_peer = request_grant_to_follow user
    comm_peer.comm_port.user.grant_to_follow self
  end

  def set_base64_file file_json, content_type, file_name
    StringIO.open(Base64.decode64(file_json)) do |data|
      data.class.class_eval { attr_accessor :original_filename, :content_type }
      data.original_filename = file_name
      data.content_type = content_type
      self.foto = data
    end
  end

  def is_admin?
    email == ADMIN_EMAIL_ADDRESS
  end

  SOCIAL_NETS_CONFIG.keys.each do |network|
    next if network.match(/_#{Rails.env}$/).present?
    
    define_method "#{network}_identity" do
      identities.where(provider: network).first
    end
    define_method "#{network}_mobile_identity" do
      identities.where(provider: network).first
    end

    define_method "connected_to_#{network}?" do
      send("#{network}_identity").present?
    end
    define_method "connected_to_#{network}_mobile?" do
      send("#{network}_identity").present?
    end
  end

  def self.admin
    User.where(email: ADMIN_EMAIL_ADDRESS).first
  end

  def self.rand_user
    dummy_username = (0..6).map { MIXED[rand(MIXED.length)] }.join
    dummy_password = (0..8).map { MIXED[rand(MIXED.length)] }.join
    foto = UserHelper::fetch_random_avatar
    foto = File.open("#{Rails.root}/spec/support/images/foto.png", 'r') unless foto.present?
    u = User.create(username: dummy_username,
                    password: dummy_password,
                    password_confirmation: dummy_password,
                    email: ADMIN_EMAIL_ADDRESS.sub(/^[^@]+/, dummy_username),
                    search_radius_meters: 1000,
                    snapshot: UserSnapshot.new(location: Location.default, cur_commit: Commit.latest),
                    foto: foto,
                    comm_port: CommPort.new(channel_enc_key: CommPort.enc_key, sys_channel_enc_key: CommPort.enc_key)
                   )
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    return nil unless auth.present?

    identity = Identity.find_with_omniauth(auth)
    auth_user = identity.user if identity.present?
    
    email_is_confirmed = auth.info.email && (auth.info.verified || auth.info.verified_email)

    if signed_in_resource.present?
      user = signed_in_resource
      if auth_user.present?
        if auth_user != user
          if (old_identity = user.identities.find{|i|i.provider==identity.provider}).present?
            # user has 2nd identity @ same provider - probably re-registered there
            old_identity.uid = identity.uid
            identity = old_identity # old is already associated with user -> update
          else
            user.identities << identity 
          end
        end
        identity.update_omniauth_attributes auth, email_is_confirmed
      else
        identity = Identity.build_with_omniauth user, auth, auth.info.email, email_is_confirmed
      end
    else
      if auth_user.present?
        user = auth_user
        identity.update_omniauth_attributes auth, email_is_confirmed
      else
        user =(auth.info.email ? User.where(:email => auth.info.email).first : nil) || User.new
        identity = Identity.build_with_omniauth user, auth, auth.info.email, email_is_confirmed
      end
    end

    user.save!

    user
  end

end

app/views/shared/_groups.html.haml
%div#groups_membership
  my memberships
  %br
  = select(:user, :group_ids, tmp_user.groups.collect{|g|[g.name, g.id]}, {}, { :multiple => true, :size => 5 })
%div#groups_created
  groups created by me
  %br
  = select(:user, :group_ids, Group.where(creator: tmp_user).collect{|g|[g.name, g.id]}, {}, { :multiple => true, :size => 5 })

  %br
  add invitation dialog
%div#group_create
  add new group

app/views/shared/_help.html.haml
#content_help{style: 'display: none;'}
  %p
    %h4 Marker
    Es gibt 2 Typen von Markern:
    %ul
      %li
        einen blauen Arbeits-Marker mit dem der Benutzer Punkte markiert die er bearbeiten möchte. Bei mouseover
        wird ein Werkzeug-Menu geöffnet.
      %li
        rote Marker kennzeichnen Points of Interest. Ein einfacher Klick öffnet das Informationsfenster des POIs.

    %h4 Einträge erstellen
    Entweder über einen Link im Werkzeug-Menu oder mit einem Doppelklick auf den Arbeits-Marker wird ein Eintrag erstellt. Ein Eintrag besteht aus einer Medien-Datei und einem Text. Andere Benutzer können einen Eintrag kommentieren, wobei dem Kommentar selbst auch wieder eine Datei angeheftet werden kann.
    
    %h4 Online / Offline
    Im Offline-Modus kann man sehen welche Karten-Kacheln bislang lokal gespeichert wurden.

app/views/shared/_peers.html.haml
/ TODO
.field{style: 'display: none;'}
  %input{type: 'checkbox', name: 'peer_channel', value: 'talk', checked: true}
    Chat
  %input{type: 'checkbox', name: 'peer_channel', value: 'map_events'}
    Map
  %input{type: 'checkbox', name: 'peer_channel', value: 'uploads'}
    Uploads
  %input{type: 'checkbox', name: 'peer_channel', value: 'all'}
    All
-# width: '100%', 
%table#followings
  -# peers followed by user and granted
  %tr
    %th{colspan: 6}
      #{t('admin.i_follow')}
  %tbody#i_follow
  -# peers followed by user and not granted
  %tr
    %th{colspan: 6}
      #{t('admin.i_want_to_follow')}
  %tbody#i_want_to_follow
  -# peers not followed by user   / and comm_peers.id is null
  %tr
    %th{colspan: 6}
      #{t('admin.i_dont_follow')}
  %tbody#i_dont_follow
  %tr
    %th{colspan: 6}
      <hr />
  -# peers that follow user
  %tr
    %th{colspan: 6}
      #{t('admin.follow_me')}
  %tbody#follow_me
  -# peers that requested grant to follow user
  %tr
    %th{colspan: 6}
      #{t('admin.want_to_follow_me')}
  %tbody#want_to_follow_me

app/views/shared/_system_dialog.html.haml
- if is_mobile
  %div{id: 'system_message_popup', 'data-role' => 'popup'}
    %a{href: '#', 'data-rel' => 'back', class: 'nav_popup_close ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right'}
      Close
    #system_message_as_popup

#tmpl_system_dialog_container{style: 'display: none;'}
  #tmpl_fullscreen_dialog{style: 'display: none;'}
    %center
      Fullscreen erlauben? Die Steuerung befindet sich im
      = image_tag 'arrow-up-right_off.png', style: 'max-width: 35px; max-height; 70px;'
      Panel
      %br
      %span{style: 'float: left;'}
        .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'enable_fullscreen'}}
          .ui-button-text
            Yes
      %span
        .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'disable_fullscreen'}}
          .ui-button-text
            No

  #tmpl_subscription_grant_request_dialog{style: 'display: none;'}
    subscription_grant_request:
    %div{style: 'float: left'}
      %img{tmpl: {src: '{user_foto_url}'}, style: 'max-width: 35px !important;'}
    %div
      %span{style: 'float: left; padding: 0px 0px 0px 5px;'}
        %a{href: '#', onclick: "javascript:APP.model().grantFollow(APP.storage().getUser({user_id}));"} grant
      %span{style: 'padding: 0px 0px 0px 5px;'}
        %a{href: '#', onclick: "javascript:APP.model().denyFollow(APP.storage().getUser({user_id}));"} deny

  #tmpl_subscription_granted_dialog{style: 'display: none;'}
    subscription_granted
    %div{style: 'float: left'}
      %img{tmpl: {src: '{user_foto_url}'}, style: 'max-width: 35px !important;'}
    %div
      %span{style: 'float: left; padding: 0px 0px 0px 5px;'}
        %a{href: '#', onclick: "javascript:APP.showPeer(APP.storage().getUser({user_id}), {id: {lastLocationId}, lat: {lastLat}, lng: {lastLng}, address: '{lastAddress}'.trim()!='' ? '{lastAddress}' : null}, 'popup');"} show

  #tmpl_peer_in_range_dialog{style: 'display: none;'}
    peer_in_range
    %div{style: 'float: left'}
      %img{tmpl: {src: '{user_foto_url}'}, style: 'max-width: 35px !important;'}
    %div
      %span{style: 'float: left; padding: 0px 0px 0px 5px;'}
        %a{href: '#', onclick: "javascript:APP.showPeer(APP.storage().getUser({user_id}), {id: {lastLocationId}, lat: {lastLat}, lng: {lastLng}, address: '{lastAddress}'.trim()!='' ? '{lastAddress}' : null}, 'popup');"} show

  #tmpl_bc_message_received_popup{style: 'display: none;'}
    %span{style: 'color:black;'}
      Conference-Message Received from {peerUsername}
      %button{class: 'activate_bc_chat'}
        show

  #tmpl_p2p_message_received_popup{style: 'display: none;'}
    %span{style: 'color:black;'}
      P2P-Message Received from {peerUsername}
      %button{class: 'activate_p2p_chat', data: {peer: {id: '{peerId}'}}}
        show

app/views/shared/_tmpl_poi_notes.html.haml
#tmpl_poi_notes_container{style: 'display: none;'}
  %div{tmpl: {id: 'poi_notes_container'}, data: {poiId: '{poi_id}'}}
    {poi_notes}
    .poi_controls
      %hr.controls_sep
      %div{style: 'float: left; margin: 0px 0px 0px 5px;'}
        = link_to image_tag('add-comment.png', style: 'height: 25px;', title: t('uploads.add_comment'), alt: t('uploads.add_comment')), '#', onclick: 'javascript:APP.poiNoteControls()'
      -# toggle bookmark/note edit
      %div{tmpl: {id: 'save-note'}, style: 'float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
        = link_to image_tag('add-bookmark.png', style: 'height: 25px;', title: t('pois.bookmark'), alt: t('pois.bookmark')), '#', onclick: "javascript:APP.bookmarkLocation({poi_id})"
      %div{tmpl: {id: 'edit-note'}, style: 'display: none; float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
        = link_to image_tag('edit-note.png', style: 'height: 25px;', title: t('locations.view_note'), alt: t('locations.view_note')), '#', onclick: "javascript:APP.view().viewBookmarkNote(APP.storage().getBookmark({location_id}))"
      %div{tmpl: {id: 'delete-note'}, style: 'display: none; float: left; margin: 0px 0px 0px 5px; padding: 0px;'}
        = link_to image_tag('delete-bookmark.png', style: 'height: 25px;', title: t('pois.delete_bookmark'), alt: t('pois.delete_bookmark')), '#', onclick: "javascript:APP.deleteBookmark({poi_id})"
      %div{style: 'float: left; margin: 0px 0px 0px 5px; padding: 0px; display: {displayDelete};'}
        = link_to image_tag('cancel.png', style: 'height: 25px;', title: t('pois.delete'), alt: t('pois.delete')), '#', onclick: "javascript:APP.deletePoi({poi_id})"

#tmpl_poi_note{style: 'display: none;'}
  .triangle-border.upload_comment{class: '{toggle}', tmpl: {toggle: 'left|right'}, style: 'vertical-align: top;', data: {id: '{poi_note_id}', index: '{i}'}}
    %table
      %tr
        %td
          %div{style: 'float: right; width: 13px; height: 13px; margin: -7px -5px 0px 0px; display: {displayDelete};'}
            = link_to image_tag('cancel.png', style: 'height: 13px;', title: t('pois.delete_note'), alt: t('pois.delete_note')), '#', onclick: "javascript:APP.deletePoiNote({poi_id}, {poi_note_id})"
          .poi_note{style: 'float: left; padding: 0px 10px 0px 0px;'}
            %a{href: '#', onclick: 'javascript:APP.view().viewAttachment({poi_note_id});'}><
              {media_file_tag}
          %div{style: 'float: left !important; text-decoration: underline; font-weight: bold; padding-right: 10px;'}><
            {username}:
          {comment}

app/views/shared/_uploads.html.haml
.modal
  .modal-dialog#upload_data_conrols
    .modal-header
      %h4.modal-title #{t('uploads.upload').html_safe}
    .modal-body
      #poi_note_input

= render partial: '/pois/form/tmpl', locals: {poi_note: PoiNote.new}
= render partial: '/shared/tmpl_poi_notes'

%iframe{id: "upload_target", src: csrf_path, name: "upload_target", style: "display:none;"}

.modal
  .modal-dialog#attachment_view_panel

app/views/shared/_uploads.mobile.html.haml
:javascript
  $("head").append("<style type='text/css'>#upload_data_panel {width: "+($(window).width()-10)+"px !important; height:"+($(window).height()-50)+"px !important; overflow: scroll;}</style>");
  var photoWidth = Math.round($(window).width() * 0.75);
  var photoHeight = Math.round($(window).height() * 0.75);
  $("head").append("<style type='text/css'>#media_input_capture, #media_input_current {width:"+photoWidth+"px;height:"+photoHeight+"px;}</style>");

#upload_data_panel{style: 'min-height: initial', data: {role: 'panel', dismissible: 'false', animate: 'true', display: 'overlay'}}
  #upload_data_panel_content
    %div{style: 'float: right; padding: 0px 0px 0px 10px;'}
      %span.ui-icon.ui-icon-circle-close{onclick: '$("#upload_data_panel").panel("close");'}
    %fieldset.upload_source_select{data: {role: 'controlgroup', type: 'horizontal'}}
      %input#data_upload_type_plain_text{type: 'radio', name: 'upload_type', value: 'plain_text', checked: true, onclick: 'APP.transfer().toggleUploadType(this)'}
      %label{'for' => 'data_upload_type_plain_text'.html_safe} #{t('uploads.plain_text').html_safe}
      %input#data_upload_type_camera{type: 'radio', name: 'upload_type', value: 'camera', onclick: 'APP.transfer().toggleUploadType(this)'}
      %label{'for' => 'data_upload_type_camera'.html_safe} #{t('uploads.camera').html_safe}
      %input#data_upload_type_file{type: 'radio', name: 'upload_type', value: 'file', onclick: 'APP.transfer().toggleUploadType(this)'}
      %label{'for' => 'data_upload_type_file'.html_safe} #{t('uploads.file').html_safe}
      %input#data_upload_type_embed{type: 'radio', name: 'upload_type', value: 'embed', onclick: 'APP.transfer().toggleUploadType(this)'}
      %label{'for' => 'data_upload_type_embed'.html_safe} #{t('uploads.embed').html_safe}
    #poi_note_input

= render partial: '/pois/form/tmpl.mobile', locals: {poi_note: PoiNote.new}
= render partial: '/shared/tmpl_poi_notes'

%iframe{id: "upload_target", name: "upload_target", style: "display:none;"}