config/routes.rb
VoyageX::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'auth/omniauth_callbacks',
                            registrations: "auth/registrations",
                            sessions: "auth/sessions" }
  devise_scope :user do
    match '/auth/:provider', to: 'sessions#create', via: [:get, :post], as: :authentication
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :authentication_callback
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/auth/facebook/disconnect', to: 'users#disconnect_from_facebook', via: [:get, :post]
    match '/auth/twitter/disconnect', to: 'users#disconnect_from_twitter', via: [:get, :post]
  end

  mount Resque::Server, at: '/4hfg398dmmnrf/resque', as: :resque_admin
  
  mount Comm::Engine => "/comm" unless Rails.env == 'test'

  resources :users, only: [:update] do
  end
  get '/users', to: 'users#users', as: :users
  get '/unread_chat_messages', to: 'users#unread_chat_messages', as: :unread_chat_messages
  put '/chat_message_received/:id', to: 'users#chat_message_received', as: :chat_message_received

  get '/location_bookmarks', to: 'main#index'
  get '/location_data/:location_id', to: 'main#location_data', as: :location_data
  get '/pois/:lat/:lng', to: 'pois#pois', as: :pois, constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                    lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  post '/sync_pois', to: 'pois#sync_pois', as: :sync_pois
  match '/pull_pois/:lat/:lng/:radius', to: 'pois#pull_pois', as: :pull_pois,
                                                              via: [:get, :post],
                                                              constraints: { lat: /([0-9]+\.[0-9]+|:[a-z]+)/,
                                                                             lng: /([0-9]+\.[0-9]+|:[a-z]+)/ }
  
  get '/manifest', to: 'main#manifest', as: :manifest
  match '/set_user_detail/:detail', to: 'users#change_details', as: :set_user_detail, via: [:get, :post]
  delete '/set_user_detail/:detail', to: 'users#delete_details'
  get '/csrf', to: 'pois#csrf', as: :csrf
  get '/poi_comments/:poi_id/:poi_note_id', to: 'pois#comments', as: :poi_comments
  get '/ping/:key', to: 'comm/comm#ping', as: :comm_ping
  put '/register', to: 'comm/comm#register', as: :comm_register

  get '/test/javascript', to: 'test#javascript', as: :test_javascript

  get '/thesis', to: 'thesis#index', as: :thesis
  
  root to: 'main#index'
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  
  MASTER = GIT_MASTER
  WORK_DIR_ROOT = "#{Rails.root}/user_repos"

  belongs_to :commit#, dependent: :destroy
  belongs_to :location
  has_many :notes, class_name: 'PoiNote', inverse_of: :poi, dependent: :destroy

  def user
    commit.user
  end
  
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController 
  include ApplicationHelper
  include PoiHelper

  #
  # FIXME there's a problem with csrf from app-cache (after updating version) - 
  #       no current_user will be set then.
  #
  #skip_before_filter :verify_authenticity_token, only: [:create, :update]
  skip_before_action :verify_authenticity_token, if: :current_user_required?

  def index
    render layout: 'uploads'
  end

  def pull_pois
    @user = tmp_user

    @user.update_attributes search_radius_meters: params[:radius]
    location = nearby_location(Location.new(latitude: params[:lat], longitude: params[:lng]), 10)
    if location.persisted?
      @user.snapshot.update_attributes location: location, lat: nil, lng: nil
    else
      @user.snapshot.update_attributes location: nil, lat: location.latitude, lng: location.longitude
    end

    #if true
    if ![:development].include?(Rails.env.to_sym)
      Resque.enqueue(PostCommit, {action: 'pull_pois',
                                  user_id: @user.id,
                                  commit_hash: params[:commit_hash]})
    else
      PostCommit.new.pull_pois @user.id,
                               params[:commit_hash],
                               false
    end

    render json: { message: 'OK' }.to_json
  end

  def sync_pois
    @user = tmp_user
    now = DateTime.now
    # required for providing user to poi_notes
    commit = @user.commits.create hash_id: "#{@user.id}.#{now.to_i}", timestamp: now
    errors = []
    min_local_time_secs_list = []
    modified_poi_data = {} # commit alomne would loose info for deleted poi-notes
    params[:pois].each do |poi_id, poi_data|
      if poi_id.to_i >= 0
        # if poi is deleted by remote user when local user is offline then it will be deleted
        # on local system as soon as local user gets online - first action is pull. all eventually
        # queued poi-changes will be deleted - so it should never happen that a user calls with
        # poi-id for a non-existing poi ...
        poi = Poi.find poi_id
        if poi_data[:action] == 'delete'
          modified_poi_data[poi.id] = HashWithIndifferentAccess.new deleted: true, poi_location_latitude: poi.location.latitude.to_f, poi_location_longitude:  poi.location.longitude.to_f 
          poi.destroy
          next
        end
      else
        # poi might already exist (nearby) - so 
        poi = nearby_poi @user, Location.new(latitude: poi_data[:location][:latitude], longitude: poi_data[:location][:longitude])
        unless poi.persisted?
          poi.commit = commit
          poi.local_time_secs = poi_id.to_i.abs 
        end
        poi.location.commit = commit unless poi.location.commit.present? # location is saved in nearby_poi if it was new
      end
      @user.locations << poi.location unless @user.locations.find {|l|l.id==poi.location.id}

      modified_poi_note_data = HashWithIndifferentAccess.new added_note_ids: [], deleted_note_ids: []

      min_local_time_secs = -1
      poi_data[:notes].each do |poi_note_id, poi_note_data|
        action = poi_note_data[:action]
        if action == 'delete'
          poi_note = PoiNote.find poi_note_id.to_i.abs
          poi.notes.delete poi_note
          modified_poi_note_data[:deleted_note_ids] << poi_note_id.to_i.abs
        else
          poi_note_local_time_secs = poi_note_id.to_i.abs # (poi_note_id.to_i/1000).round.abs
          min_local_time_secs = poi_note_local_time_secs if (min_local_time_secs == -1) || (poi_note_local_time_secs < min_local_time_secs)

          file = poi_note_data[:file]
          if file.present? || (embed = poi_note_data[:embed]).present?
            upload = Upload.new(attached_to: PoiNote.new(poi: poi, commit: commit, text: poi_note_data[:text], local_time_secs: poi_note_local_time_secs))
            upload.attached_to.attachment = upload
            if file.present?
              upload.build_entity file.content_type, file: file
            else
              upload.build_entity :embed, text: embed[:content], embed_type: UploadEntity::Embed.get_embed_type(embed[:content])
            end
            poi_note = upload.attached_to
          else
            poi_note = PoiNote.new(poi: poi, commit: commit, text: poi_note_data[:text], local_time_secs: poi_note_local_time_secs)
          end
          poi.notes << poi_note
          modified_poi_note_data[:added_note_ids] << poi_note_id.to_i.abs
        end
      end
      
      if poi.save
        modified_poi_data[poi.id] = modified_poi_note_data
        min_local_time_secs_list << min_local_time_secs
      else
        errors << poi.errors.full_messages
      end
    end
    commit.update_attribute :local_time_secs, min_local_time_secs_list.min

    #if true
    if ![:development].include?(Rails.env.to_sym)
      Resque.enqueue(PostCommit, {action: 'sync_pois',
                                  commit_id: commit.id,
                                  modified_poi_data: modified_poi_data})
    else
      PostCommit.new.sync_pois commit.id,
                               modified_poi_data,
                               false
    end

    render json: { errors: errors }.to_json
  end

  # api
  def pois
    user = current_user || tmp_user

    pois_json = []
    @pois = nearby_pois Location.new(latitude: params[:lat], longitude: params[:lng]), (user.search_radius_meters||1000)
    @pois.each do |poi|
      pois_json << poi_json(poi)
    end
    
    render json: pois_json.to_json
  end

  # api
  def comments
    user = current_user || tmp_user
    if params[:poi_note_id] != '-1'
      poi_note = PoiNote.find(params[:poi_note_id])
      poi = poi_note.poi
    else
      poi_note = nil
      poi = Poi.find(params[:poi_id]) if params[:poi_id].present?
    end

    poi_json = poi_json poi
    poi_json[:notes] = poi_notes_as_list poi, poi_note

    render json: {poi: poi_json}.to_json
  end

  def csrf
    render "shared/csrf", layout: 'uploads'
  end

  protected

  # @see skip_before_action
  def current_user_required?
    [:pull_pois, :sync_pois, :destroy, :pois, :comments].include? action_name.to_sym
  end

end

app/helpers/poi_helper.rb
module PoiHelper
  include ::GeoUtils

  def add_attachment_to_poi_note_json upload, poi_note_json
    if upload.entity.is_a? UploadEntity::Mediafile
      case upload.entity.content_type.match(/^[^\/]+/)[0]
      when 'image'
        geometry = Paperclip::Geometry.from_file(upload.entity.file)
        poi_note_json[:attachment] = { content_type: upload.entity.file.content_type, id: upload.id, url: upload.entity.file.url, width: geometry.width.to_i, height: geometry.height.to_i }
      when 'audio'
        poi_note_json[:attachment] = { content_type: upload.entity.file.content_type, id: upload.id, url: upload.entity.file.url }
      when 'video'
        poi_note_json[:attachment] = { content_type: upload.entity.file.content_type, id: upload.id, url: upload.entity.file.url }
      else
        poi_note_json[:attachment] = { content_type: 'unknown/unknown', id: upload.id, url: upload.entity.file.url }
      end
    elsif upload.entity.is_a? UploadEntity::Embed
      case upload.entity.embed_type.match(/^[^\/]+/)[0]
      when 'image'
        poi_note_json[:attachment] = { content_type: "embed:#{upload.entity.embed_type}", id: upload.id, content: upload.entity.text, width: -1, height: -1 }
      when 'audio'
        poi_note_json[:attachment] = { content_type: "embed:#{upload.entity.embed_type}", id: upload.id, content: upload.entity.text }
      when 'video'
        poi_note_json[:attachment] = { content_type: "embed:#{upload.entity.embed_type}", id: upload.id, content: upload.entity.text }
      else
        poi_note_json[:attachment] = { content_type: 'embed:unknown/unknown', id: upload.id, content: upload.entity.text }
      end
    else
      poi_note_json[:attachment] = { content_type: 'unknown/unknown', id: upload.id, url: nil, width: -1, height: -1 }
    end
  end
  
  def poi_json poi
    poi_json = { id: poi.id,
                 lat: poi.location.latitude,
                 lng: poi.location.longitude,
                 address: shorten_address(poi.location),
                 locationId: poi.location.id }
  end
  
  def poi_note_json poi_note, with_poi = true
    poi_note_json = { id: poi_note.id,
                      user: { id: poi_note.user.id,
                              username: poi_note.user.username },
                      text: poi_note.text }
    poi_note_json[:poi] = poi_json poi_note.poi if with_poi
    add_attachment_to_poi_note_json poi_note.attachment, poi_note_json if poi_note.attachment.present?
    poi_note_json
  end

  def poi_notes_as_list poi, poi_note
    poi_notes = []
    poi.notes.where('comments_on_id is null').each do |p_n|
      poi_notes << poi_note_json(p_n, false)
      p_n.comments.each do |p_n_2|
        poi_notes << poi_note_json(p_n_2, false)
        if poi_note.present? && p_n_2 == poi_note
          # only recurse for requested
          addToThread poi_note, poi_notes
        end
      end
    end
    poi_notes
  end

  def addToThread poi_note, comments
    poi_note.comments.each do |p_n|
      comments << poi_note_json(p_n, false)
      addToThread p_n, comments
    end
  end

end

app/views/pois/form/_tmpl.html.haml
#tmpl_poi_note_input{style: 'display: none;'}
  .messages
    %div{tmpl: {id: :upload_error}}
    %div{tmpl: {id: :upload_message}}
    %div{tmpl: {id: :upload_progress}}
  %div{tmpl: {id: :upload_form_ui}}
    .field
      %span{style: 'float: left; padding-right: 20px;'}
        #{t('uploads.comment')}
      = text_area_tag 'upload_comment[text]', '', id: ':remove', 'tmpl-id' => 'upload_comment'
    %div{tmpl: {id: :attachment_form_ui}}
      %input{type: 'radio', name: 'upload_type', value: 'plain_text', checked: true, onclick: 'APP.transfer().toggleUploadType(this)'}
        #{t('uploads.select_plain_text').html_safe} 
      %input{type: 'radio', name: 'upload_type', value: 'camera', onclick: 'APP.transfer().toggleUploadType(this)'}
        #{t('uploads.select_camera').html_safe} 
      %input{type: 'radio', name: 'upload_type', value: 'file', onclick: 'APP.transfer().toggleUploadType(this)'}
        #{t('uploads.select_file').html_safe}
      %input{type: 'radio', name: 'upload_type', value: 'embed', onclick: 'APP.transfer().toggleUploadType(this)'}
        #{t('uploads.select_embed').html_safe}
      %div{tmpl: {id: :upload_plain_text_container}}
        .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'plain_text_upload_btn'}}
          .ui-button-text
            #{t('uploads.upload_plain_text').html_safe}
      %div{tmpl: {id: :upload_cam_container}, style: 'display: none;'}
        = render partial: '/pois/form/tmpl_camera_data', locals: {poi_note: poi_note}
      %div{tmpl: {id: :upload_file_container}, style: 'display: none;'}
        -#%script
        -#  var updateActionPathTmpl = '#{poi_note_path(id: ':comments_on_id')}';
        = form_for poi_note, url: '#', remote: true, :html => { class: nil, multipart: true, 'tmpl-id' => 'upload_form', target: 'upload_target', 'data-poiId' => ':poi_id', 'data-commentsOnId' => ':comments_on_id' } do |f|
          = render partial: '/pois/form/tmpl_file_data', locals: {poi_note: poi_note, f: f}
          = hidden_field_tag 'location[latitude]', '', id: ':remove', 'tmpl-id' => 'location_latitude'
          = hidden_field_tag 'location[longitude]', '', id: ':remove', 'tmpl-id' => 'location_longitude'
      %div{tmpl: {id: :upload_embed_container}, style: 'display: none;'}
        = text_area_tag 'upload_comment[embed]', '', id: ':remove_upload_comment_embed', 'tmpl-id' => 'embed'
        %br
        .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'embed_upload_btn'}}
          .ui-button-text
            #{t('uploads.upload_embed').html_safe}

app/views/pois/form/_tmpl.mobile.html.haml
#tmpl_poi_note_input{style: 'display: none;'}
  .messages
    %div{tmpl: {id: :upload_error}}
    %div{tmpl: {id: :upload_message}}
    %div{tmpl: {id: :upload_progress}}
  .field
    %span{style: 'float: left; padding-right: 20px;'}
      #{t('uploads.comment')}
    = text_area_tag 'upload_comment[text]', '', id: ':remove', 'tmpl-id' => 'upload_comment'
  .upload_data_container{style: 'width: 100%;', tmpl: {id: :upload_plain_text_container}}
    .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'plain_text_upload_btn'}}
      .ui-button-text
        #{t('uploads.upload_plain_text').html_safe}
  .upload_data_container{style: 'display: none; width: 100%;', tmpl: {id: :upload_cam_container}}
    /= render partial: '/pois/form/camera_data.mobile', locals: {poi_note: poi_note}
    = render partial: '/pois/form/tmpl_camera_data.mobile', locals: {poi_note: poi_note}
  .upload_data_container{style: 'display: none; width: 100%;', tmpl: {id: :upload_file_container}}
    -#%script
    -#  var updateActionPathTmpl = '#{poi_note_path(id: ':comments_on_id')}';
    = form_for poi_note, url: '#', remote: true, :html => { class: nil, multipart: true, 'tmpl-id' => 'upload_form', target: 'upload_target', 'data-poiId' => ':poi_id', 'data-commentsOnId' => ':comments_on_id' } do |f|
      = render partial: '/pois/form/tmpl_file_data', locals: {poi_note: poi_note, f: f}
      = hidden_field_tag 'location[latitude]', '', id: ':remove', 'tmpl-id' => 'location_latitude'
      = hidden_field_tag 'location[longitude]', '', id: ':remove', 'tmpl-id' => 'location_longitude'
  .upload_data_container{style: 'display: none; width: 100%;', tmpl: {id: :upload_embed_container}}
    = text_area_tag 'upload_comment[embed]', '', id: ':remove_upload_comment_embed', 'tmpl-id' => 'embed'
    %br
    .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'embed_upload_btn'}}
      .ui-button-text
        #{t('uploads.upload_embed').html_safe}

app/views/pois/form/_tmpl_camera_data.html.haml
%span
  %button{tmpl: {id: 'media_input_init'}}
    #{t('uploads.start_camera').html_safe}
%br
#media_input_container
  #video_viewer
    %video{tmpl: {id: 'media_input_capture'}, style: 'width: 307px; height: 250px;', autoplay: true}
  #video_snapshot
    %img{tmpl: {id: 'media_input_current'}, src: '', style: 'width: 307px; height: 250px;'}
  %canvas{tmpl: {id: 'media_input_display'}, style: 'display: none;'}
  %br{style: 'clear: both;'}
  .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'media_input_capture_btn'}}
    .ui-button-text
      #{t('uploads.take_shot').html_safe}
  .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'media_input_stop_btn'}}
    .ui-button-text
      Stop
  .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'media_input_upload_btn'}}
    .ui-button-text
      #{t('uploads.upload_photo').html_safe}

app/views/pois/form/_tmpl_camera_data.mobile.html.haml
%span{style: 'float: left;'}
  %button{tmpl: {id: 'media_input_init'}}
    #{t('uploads.start_camera')}
  = link_to '#', '#media_input_panel', id: ':remove', 'tmpl-id' => 'media_input_panel_show'
%div{tmpl: {id: :upload_form_ui}}
  %div{tmpl: {id: :media_input_container}, style: 'display: none; text-align: center;'}
    %img{tmpl: {id: 'media_input_current'}, src: ''}
    .ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-only{tmpl: {id: 'media_input_upload_btn'}}
      .ui-button-text
        #{t('uploads.upload_photo').html_safe}

app/views/pois/form/_tmpl_file_data.html.haml
%div{tmpl: {id: :upload_file_controls}}
  = hidden_field_tag 'poi_note[text]', '', 'tmpl-id' => 'upload_comment_text'
  %span{style: 'float: left;'}
    = f.file_field 'file', 'tmpl-id' => 'fileupload', accept: UploadEntity::Mediafile::ACCEPTED_CONTENT_TYPES.join(',')
  %button.show-page-loading-msg{tmpl: {id: 'upload_button'}, data: {type: 'json', theme: 'a', textonly: 'false', textvisible: 'true', msgtext: 'Loading'}}
    #{t('uploads.upload').html_safe}